name: GitHub Pages
run-name: ${{ github.actor }} exam app 🚀
on:
  push:
    branches:
      - exam
jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install npm deps
        working-directory: ./exam
        run: npm ci

      - name: Build app
        working-directory: ./exam
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./exam/dist
